backend:
  name: github
  repo: pranjalpruthi/montreal
  branch: main

local_backend: true

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

i18n:
  structure: multiple_folders
  locales: [en, fr]
  default_locale: en

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    extension: "mdx"
    format: "frontmatter"
    i18n: true
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Description", name: "description", widget: "text", i18n: true }
      - { label: "Publish Date", name: "date", widget: "datetime", i18n: duplicate }
      - { label: "Author", name: "author", widget: "string", required: false, i18n: duplicate }
      - { label: "Thumbnail", name: "thumbnail", widget: "image", required: false, i18n: duplicate }
      - { label: "Tags", name: "tags", widget: "list", required: false, i18n: duplicate }
      - { label: "Featured", name: "featured", widget: "boolean", default: false, required: false, i18n: duplicate }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }
